### ISSUE TITLE
feat: tooltip for contours & wires

### ISSUE THREAD

**Issue by masfaraud** [Dessia-tech/plot_data#149]
Would be nice to display a tooltip when hovering a contour or a wire (shape)
need: have infos on a wire

**Comment by AxelRinghausen** [comment]
![image](https://user-images.githubusercontent.com/50665039/157889101-7d73540a-4bf8-44a6-8ccd-9464dda146e9.png)
The wires are the colored set of lines (simply several line segments put next to each other, because I don't think there is a shape for that yet). 
The contours are the colored boxes. 
The labeling of the tool-tip don't have to be dynamic, I just want to store information (just a string would be nice) in these geometric shape as I create them. 
Right now, only the contour is clickable.

**Comment by GhislainJ** [comment]
Does contour mean the wire around the area or the area itself ?
